advertgenerator:
  target:
    scheme: https
    host: api-gateway-tvexvi6w2q-uc.a.run.app
#    host: yajb-api-gateway.fly.dev
  tenant:
    id: reeljobs
    secret: reeljobs
  oidc:
    token-endpoint: https://yetanotherjobboard.eu.auth0.com/oauth/token
    client-id: kHOgCKg98UI66seLJ6ArQSkgDx3OyljC
    client-secret: change-me
  user:
    username: trafficgenerator@yajb.com
    password: change-me
  max-adverts-to-generate: 10000
#  max-adverts-to-generate: 100
