advertgenerator:
  target:
    scheme: http
    host: localhost:8000
  tenant:
    id: reeljobs
    secret: reeljobs
  oidc:
    token-endpoint: http://localhost:10000/realms/yajb-realm/protocol/openid-connect/token
    client-id: yajb-test
    client-secret: keycloak-ignores-this
  user:
    username: trafficgenerator@yajb.com
    password: password


  logging:
    pattern.console: "%-5level : %msg%n%wEx"
