advertgenerator:
  target:
    scheme: https
    host: yajb-api-gateway.fly.dev
  tenant:
    id: reeljobs
    secret: reeljobs
  oidc:
    token-endpoint: https://yetanotherjobboard.eu.auth0.com/oauth/token
    client-id: kHOgCKg98UI66seLJ6ArQSkgDx3OyljC
    client-secret: CHANGEME
  user:
    username: trafficgenerator@yajb.com
    password: CHANGEME
