name: Run Load Tests
on:
  workflow_dispatch:
    inputs:
      max-users:
        required: true
        description: max users
        default: 10
      max-loops:
        required: true
        description: max loops
        default: 10
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: run tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: generateSources gatlingRun
        env:
          MAX_USERS: ${{ github.event.inputs.max-users }}
          MAX_LOOPS: ${{ github.event.inputs.max-loops }}

